# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'dagen',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personeelsnummer', models.IntegerField()),
                ('voornaam', models.CharField(max_length=100)),
                ('tussenvoegsels', models.CharField(blank=True, max_length=20)),
                ('achternaam', models.CharField(max_length=100)),
                ('fte', models.FloatField(default=1)),
                ('ADV', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feestdagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrije_dag', models.CharField(max_length=100)),
                ('dag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Dagen')),
            ],
            options={
                'verbose_name_plural': 'feestdagen',
            },
        ),
        migrations.CreateModel(
            name='Functie',
            fields=[
                ('naam', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uren_dienstverband', models.IntegerField(default=36)),
                ('opleidingsdagen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supervisie_krijgen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('werkbegeleiding_krijgen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('studieduur_krijgen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('werkoverleg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('meelezen_verslagen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supervisie_geven', models.DecimalField(decimal_places=2, max_digits=5)),
                ('werkbegeleiding_geven', models.DecimalField(decimal_places=2, max_digits=5)),
                ('praktijkopleiding_geven', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teamleider_taken', models.DecimalField(decimal_places=2, max_digits=5)),
                ('KP_werkzaamheden', models.DecimalField(decimal_places=2, max_digits=5)),
                ('overig', models.DecimalField(decimal_places=2, max_digits=5)),
                ('niet_benoemd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vakantie', models.DecimalField(decimal_places=2, max_digits=5)),
                ('levensloop', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(choices=[('OLD', 'opleidingsdagen'), ('SV_K', 'supervisie krijgen'), ('WBG_K', 'werkbegeleiding krijgen'), ('SD_K', 'studieduur krijgen'), ('WO', 'werkoverleg'), ('MLV', 'meelezen verslag'), ('SV_G', 'supervisie geven'), ('WBG_G', 'werkbegeleiding_geven'), ('PO_G', 'praktijkopleiding geven'), ('TLT', 'taken teamleider'), ('KP', 'KP werkzaamheden'), ('OV', 'overig'), ('NB', 'niet benoemd')], default='OV', max_length=5)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField()),
                ('hoeveelheid', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('medewerker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Employee')),
            ],
            options={
                'verbose_name_plural': 'planningen',
            },
        ),
        migrations.CreateModel(
            name='Regio',
            fields=[
                ('naam', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('regiomanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='productiviteit.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Timechart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boekjaar', models.IntegerField(null=True)),
                ('periode', models.IntegerField(null=True)),
                ('nacalculatie', models.CharField(blank=True, default='', max_length=100)),
                ('naam', models.CharField(blank=True, default='', max_length=100)),
                ('datum', models.DateField(null=True)),
                ('aantal', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('soort', models.CharField(blank=True, default='', max_length=10)),
                ('code', models.CharField(blank=True, default='', max_length=20)),
                ('kostendrager', models.CharField(blank=True, default='', max_length=10)),
                ('jaar', models.IntegerField(null=True)),
                ('maand', models.IntegerField(null=True)),
                ('direct', models.CharField(blank=True, default='', max_length=10)),
                ('personeelsnummer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnummer', to='productiviteit.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='VerdeeldePlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('verdeling', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Planning')),
            ],
            options={
                'verbose_name_plural': 'verdeeldeplanningen',
            },
        ),
        migrations.CreateModel(
            name='Vestiging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('bij_regio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Regio')),
                ('teamleider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamleider', to='productiviteit.Employee')),
            ],
            options={
                'verbose_name_plural': 'vestigingen',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='functie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Functie'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='vestiging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productiviteit.Vestiging'),
        ),
    ]
