# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productiviteit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechart',
            name='aantal',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
