# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productiviteit', '0002_auto_20161217_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timechart',
            name='personeelsnummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnummer', to='productiviteit.Employee'),
        ),
        migrations.AlterField(
            model_name='vestiging',
            name='teamleider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamleider', to='productiviteit.Employee'),
        ),
    ]
